version: '3.4'

services:
  server:
    build:
      dockerfile: TicTacToe.Api/Dockerfile
    container_name: 'server'
    ports:
      - '5035:80'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      
  client:
    build:
      context: ./TicTacToe.Client.Vue
      dockerfile: ./Dockerfile
    ports:
      - '3000:8080'
      
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "game"
      
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"    
   